[2023-08-08T07:26:33.682+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_w_postgres_v2.insert_data_to_postgres scheduled__2023-08-07T00:00:00+00:00 [queued]>
[2023-08-08T07:26:33.690+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_w_postgres_v2.insert_data_to_postgres scheduled__2023-08-07T00:00:00+00:00 [queued]>
[2023-08-08T07:26:33.690+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 7
[2023-08-08T07:26:33.702+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): insert_data_to_postgres> on 2023-08-07 00:00:00+00:00
[2023-08-08T07:26:33.707+0000] {standard_task_runner.py:57} INFO - Started process 2562 to run task
[2023-08-08T07:26:33.710+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_w_postgres_v2', 'insert_data_to_postgres', 'scheduled__2023-08-07T00:00:00+00:00', '--job-id', '1104', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgresql.py', '--cfg-path', '/tmp/tmpuylwucdm']
[2023-08-08T07:26:33.713+0000] {standard_task_runner.py:85} INFO - Job 1104: Subtask insert_data_to_postgres
[2023-08-08T07:26:33.762+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_w_postgres_v2.insert_data_to_postgres scheduled__2023-08-07T00:00:00+00:00 [running]> on host e3ce6cb94b48
[2023-08-08T07:26:33.801+0000] {abstractoperator.py:598} ERROR - Exception rendering Jinja template for task 'insert_data_to_postgres', field 'sql'. Template: "\n            INSERT INTO dag_runs (dt, dag) values ('{{ ds }}', '{{ dag.dag_ id}}')\n        "
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 155, in render_template
    template = jinja_env.from_string(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 2, in template
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'id'
[2023-08-08T07:26:33.803+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 155, in render_template
    template = jinja_env.from_string(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 2, in template
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'id'
[2023-08-08T07:26:33.813+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_w_postgres_v2, task_id=insert_data_to_postgres, execution_date=20230807T000000, start_date=20230808T072633, end_date=20230808T072633
[2023-08-08T07:26:33.822+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1104 for task insert_data_to_postgres (expected token 'end of print statement', got 'id'; 2562)
[2023-08-08T07:26:33.843+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-08T07:26:33.863+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
