[2023-08-08T03:49:02.540+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v07.greet scheduled__2022-01-06T00:00:00+00:00 [queued]>
[2023-08-08T03:49:02.552+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v07.greet scheduled__2022-01-06T00:00:00+00:00 [queued]>
[2023-08-08T03:49:02.556+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-08-08T03:49:02.575+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): greet> on 2022-01-06 00:00:00+00:00
[2023-08-08T03:49:02.583+0000] {standard_task_runner.py:57} INFO - Started process 2029 to run task
[2023-08-08T03:49:02.591+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v07', 'greet', 'scheduled__2022-01-06T00:00:00+00:00', '--job-id', '326', '--raw', '--subdir', 'DAGS_FOLDER/simple_print.py', '--cfg-path', '/tmp/tmp1y2wlar7']
[2023-08-08T03:49:02.595+0000] {standard_task_runner.py:85} INFO - Job 326: Subtask greet
[2023-08-08T03:49:02.696+0000] {task_command.py:410} INFO - Running <TaskInstance: our_dag_with_python_operator_v07.greet scheduled__2022-01-06T00:00:00+00:00 [running]> on host e301933437eb
[2023-08-08T03:49:02.816+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2023-08-08T03:49:02.824+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 2029. PIDs of all processes in the group: [2029]
[2023-08-08T03:49:02.826+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 2029
[2023-08-08T03:49:02.882+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-08-08T03:49:02.960+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1525, in _execute_task_with_callbacks
    self.clear_xcom_data()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 878, in clear_xcom_data
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/api_internal/internal_api_call.py", line 112, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 616, in clear
    query.delete()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3225, in delete
    execution_options={"synchronize_session": synchronize_session},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 335, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1587, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1954, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2138, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1911, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.7/encodings/utf_8.py", line 15, in decode
    def decode(input, errors='strict'):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-08-08T03:49:03.018+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=our_dag_with_python_operator_v07, task_id=greet, execution_date=20220106T000000, start_date=20230808T034902, end_date=20230808T034903
[2023-08-08T03:49:03.068+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 326 for task greet (Task received SIGTERM signal; 2029)
[2023-08-08T03:49:03.188+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2029, status='terminated', exitcode=1, started='03:49:01') (2029) terminated with exit code 1
[2023-08-08T03:49:03.191+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 143
[2023-08-08T03:49:03.293+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
