[2023-08-08T07:26:22.457+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_w_postgres_v2.insert_data_to_postgres manual__2023-08-08T07:26:19.939262+00:00 [queued]>
[2023-08-08T07:26:22.465+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_w_postgres_v2.insert_data_to_postgres manual__2023-08-08T07:26:19.939262+00:00 [queued]>
[2023-08-08T07:26:22.466+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-08-08T07:26:22.478+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): insert_data_to_postgres> on 2023-08-08 07:26:19.939262+00:00
[2023-08-08T07:26:22.482+0000] {standard_task_runner.py:57} INFO - Started process 2560 to run task
[2023-08-08T07:26:22.487+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_w_postgres_v2', 'insert_data_to_postgres', 'manual__2023-08-08T07:26:19.939262+00:00', '--job-id', '1103', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgresql.py', '--cfg-path', '/tmp/tmp4cffwtrr']
[2023-08-08T07:26:22.489+0000] {standard_task_runner.py:85} INFO - Job 1103: Subtask insert_data_to_postgres
[2023-08-08T07:26:22.539+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_w_postgres_v2.insert_data_to_postgres manual__2023-08-08T07:26:19.939262+00:00 [running]> on host e3ce6cb94b48
[2023-08-08T07:26:22.579+0000] {abstractoperator.py:598} ERROR - Exception rendering Jinja template for task 'insert_data_to_postgres', field 'sql'. Template: "\n            INSERT INTO dag_runs (dt, dag) values ('{{ ds }}', '{{ dag.dag_ id}}')\n        "
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 155, in render_template
    template = jinja_env.from_string(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 2, in template
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'id'
[2023-08-08T07:26:22.581+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 155, in render_template
    template = jinja_env.from_string(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 2, in template
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'id'
[2023-08-08T07:26:22.592+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_w_postgres_v2, task_id=insert_data_to_postgres, execution_date=20230808T072619, start_date=20230808T072622, end_date=20230808T072622
[2023-08-08T07:26:22.600+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1103 for task insert_data_to_postgres (expected token 'end of print statement', got 'id'; 2560)
[2023-08-08T07:26:22.618+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-08T07:26:22.636+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
