[2023-08-08T07:32:53.258+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_w_postgres_v2.insert_data_to_postgres manual__2023-08-08T07:27:49.603497+00:00 [queued]>
[2023-08-08T07:32:53.264+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_w_postgres_v2.insert_data_to_postgres manual__2023-08-08T07:27:49.603497+00:00 [queued]>
[2023-08-08T07:32:53.265+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 6
[2023-08-08T07:32:53.275+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): insert_data_to_postgres> on 2023-08-08 07:27:49.603497+00:00
[2023-08-08T07:32:53.279+0000] {standard_task_runner.py:57} INFO - Started process 2936 to run task
[2023-08-08T07:32:53.283+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_w_postgres_v2', 'insert_data_to_postgres', 'manual__2023-08-08T07:27:49.603497+00:00', '--job-id', '1112', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgresql.py', '--cfg-path', '/tmp/tmprzx2x75v']
[2023-08-08T07:32:53.286+0000] {standard_task_runner.py:85} INFO - Job 1112: Subtask insert_data_to_postgres
[2023-08-08T07:32:53.340+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_w_postgres_v2.insert_data_to_postgres manual__2023-08-08T07:27:49.603497+00:00 [running]> on host e3ce6cb94b48
[2023-08-08T07:32:53.422+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Zack' AIRFLOW_CTX_DAG_ID='dag_w_postgres_v2' AIRFLOW_CTX_TASK_ID='insert_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2023-08-08T07:27:49.603497+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-08T07:27:49.603497+00:00'
[2023-08-08T07:32:53.423+0000] {sql.py:265} INFO - Executing: 
            INSERT INTO dag_runs (dt, dag_id) values ('2023-08-08', 'dag_w_postgres_v2')
        
[2023-08-08T07:32:53.433+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-08-08T07:32:53.479+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-08-08T07:32:53.488+0000] {sql.py:375} INFO - Running statement: 
            INSERT INTO dag_runs (dt, dag_id) values ('2023-08-08', 'dag_w_postgres_v2')
        , parameters: None
[2023-08-08T07:32:53.492+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2023-08-08, dag_w_postgres_v2) already exists.

[2023-08-08T07:32:53.503+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_w_postgres_v2, task_id=insert_data_to_postgres, execution_date=20230808T072749, start_date=20230808T073253, end_date=20230808T073253
[2023-08-08T07:32:53.512+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1112 for task insert_data_to_postgres (duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2023-08-08, dag_w_postgres_v2) already exists.
; 2936)
[2023-08-08T07:32:53.536+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-08T07:32:53.553+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
